copy-on-select = true

[cursor]
shape = 'block'

[fonts]
size = 20
features = []
use-drawable-chars = true
symbol-map = []
disable-warnings-not-found = false
additional-dirs = []

[fonts.regular]
family = "Iosevka"
style = "default"

[fonts.bold]
family = "Iosevka"
style = "default"

[fonts.italic]
family = "Iosevka"
style = "default"

[fonts.bold-italic]
family = "Iosevka"
style = "default"

[renderer]
backend = "Vulkan"
