copy-on-select = true
theme = "EspressoLibre"
#theme = "Elemental"

[cursor]
shape = 'block'

[colors]
hint-foreground = '#181818'  # Text color for hint labels
hint-background = '#f4bf75'  # Background color for hint labels

[fonts]
size = 20
family = "LiberationMono"
features = []
use-drawable-chars = true
symbol-map = []
disable-warnings-not-found = false
additional-dirs = []

[renderer]
backend = "Vulkan"

[hints]
# Characters used for hint labels (should be easy to type)
alphabet = "jfkdls;ahgurieowpq"

# URL hint example
[[hints.rules]]
#regex = "(https://|http://)[^\u{0000}-\u{001F}\u{007F}-\u{009F}<>\"\\s{-}\\^⟨⟩`\\\\]+"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
post-processing = true
persist = true

[hints.rules.action]
command = "xdg-open"  # Linux/BSD
# command = "open"    # macOS
# command = "explorer"  # Windows

[hints.rules.mouse]
enabled = true
mods = []

[hints.rules.binding]
key = "e"
mods = ["Control", "Shift"]

[navigation]
mode = "Plain" # this disables panes and tabs

[window]
opacity = 0.9
decorations = "enabled"
blur = true
