#!/bin/sh

#display -window root /mnt/documents/d/Images/French_Polynesia.jpg &
feh --bg-scale ~/documents/Images/French_Polynesia.jpg &

xbindkeys
setxkbmap -model pc105 -layout us -variant altgr-intl -option compose:menu
xset m 0.7 1.6
xset dpms 0 120 600
firefox &

exit 0

# vi: ft=sh:
