#!/bin/sh

# Load some defaults for each user
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

#display -window root /mnt/documents/d/Images/French_Polynesia.jpg &
feh --bg-fill ~/documents/Images/victorpks-vikings-edit.jpg &

# Set a few variables that aren't by i3 (this fixes slow startup times 
# of some applications, like Thunar and Firefox)
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &

xbindkeys
setxkbmap -model pc105 -layout us -variant altgr-intl -option compose:menu
xset m 0.7 1.6
xset dpms 0 120 600
xrandr --dpi 96
lxsession &
parcellite &
firefox &
kitty &
kitty &

exit 0

# vi: ft=sh:
