#!/bin/sh

#display -window root /home/gianluca/Downloads/wallpaper2.jpg &
display -window root /home/gianluca/Downloads/wallpaper-beksinski001.jpg &

xbindkeys
xset m 0.7 2
xset dpms 0 900 2750
firefox &

exit 0

# vi: ft=sh:
