icons = "awesome"
[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#555753"
idle_fg = "#ffffff"
info_bg = "#120d11"
info_fg = "#c4a000"

[[block]]
block = "focused_window"
max_width = 24

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
ip = false
speed_up = true
speed_down = true
bitrate = true
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 80
warning = 10.0
alert = 5.0

[[block]]
block = "disk_space"
path = "/mnt/documents/c"
alias = "C"
info_type = "available"
unit = "GB"
interval = 80
warning = 10.0
alert = 5.0

[[block]]
block = "disk_space"
path = "/mnt/documents/d"
alias = "D"
info_type = "available"
unit = "GB"
interval = 80
warning = 10.0
alert = 5.0

[[block]]
block = "disk_space"
path = "/media/private/"
alias = "Private"
info_type = "available"
unit = "GB"
interval = 80
warning = 10.0
alert = 5.0

[[block]]
block = "sound"

[[block]]
block = "music"
buttons = ["play", "next", "prev"]

[[block]]
block = "time"
interval = 3
format = "%a %d/%m %R"
