[theme]
name = "solarized-light"
[theme.overrides]
idle_bg = "#163e7b"
idle_fg = "#fbf9fe"
critical_bg = "#ece169"
critical_fg = "#d7001c"
[icons]
name = "awesome"
[icons.overrides]
cpu = "  "
memory_mem = "  "
music = "  "

[[block]]
block = "focused_window"
max_width = 60

[[block]]
block = "cpu"
per_core = true
interval = 1
format = "{barchart} {utilization}%"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 120
warning = 10.0
alert = 5.0

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
max_width = 35
dynamic_width = true
on_collapsed_click = "spotify"

[[block]]
block = "battery"
interval = 20
format = "{percentage}% ({time}H)"
good = 70
info = 60
warning = 30
critical = 15

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
locale = "it_IT"
