[theme]
name = "solarized-light"
[theme.overrides]
idle_bg = "#163e7b"
idle_fg = "#fbf9fe"
critical_bg = "#ece169"
critical_fg = "#d7001c"
[icons]
name = "awesome"
[icons.overrides]
cpu = "  "
memory_mem = "  "
music = "  "
backlight_empty = " ☀ "
backlight_full = " ☀ "
backlight_1 = " ☀ "
backlight_2 = " ☀ "
backlight_3 = " ☀ "
backlight_4 = " ☀ "
backlight_5 = " ☀ "
backlight_6 = " ☀ "
backlight_7 = " ☀ "
backlight_8 = " ☀ "
backlight_9 = " ☀ "
backlight_10 = " ☀ "
backlight_11 = " ☀ "
backlight_12 = " ☀ "
backlight_13 = " ☀ "

[[block]]
block = "focused_window"
max_width = 60

[[block]]
block = "cpu"
per_core = false
interval = 1
format = "{barchart} {utilization}%"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 120
warning = 10.0
alert = 5.0

[[block]]
block = "disk_space"
path = "/home"
alias = "home"
info_type = "available"
unit = "GB"
interval = 120
warning = 10.0
alert = 5.0

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "amdgpu_bl0"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
max_width = 35
dynamic_width = true
on_collapsed_click = "spotify"

[[block]]
block = "battery"
interval = 20
format = "{percentage}% ({time}H)"
good = 70
info = 60
warning = 30
critical = 15

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 60

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
locale = "it_IT"
