#! /bin/sh

bspc config border_width        1
bspc config window_gap			0
bspc config top_padding			16
bspc config left_padding		0
bspc config bottom_padding		0
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer false

bspc monitor -d I II III IV V VI VII

bspc desktop ^1 --layout tiled

bspc rule -a Firefox state=tiled desktop=^1
bspc rule -a Gimp desktop=^5 follow=on state=tiled
bspc rule -a mpv state=floating
bspc rule -a sxiv state=floating
bspc rule -a Skype state=floating
bspc rule -a lxappearance state=tiled

# Launch various programs
~/.config/bspwm/bspwm_launcher &
