[config]
library_tabs = "albums, artists, playlists, podcasts"

[theme]
background = "#181818"
primary = "#F1F1F1"
secondary = "#DCDCDC"
title = "#D7571E"
playing = "#D72F1E"
playing_selected = "#D79F1E"
playing_bg = "#181818"
highlight = "#B9451D"
highlight_bg = "#000000"
error = "#FFE4E4"
error_bg = "#5B0505"
statusbar = "#000000"
statusbar_progress = "#FB321C"
statusbar_bg = "#EFEAE8"
cmdline = "#FFD599"
cmdline_bg = "#171717"
